// Autogenerated by Thrift Compiler (0.11.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "context"
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
        "OpenStars/TrustKeys/ContactStore"
)


func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  TDataResult getData(TKey key)")
  fmt.Fprintln(os.Stderr, "  TErrorCode putData(TKey key, TKContact data)")
  fmt.Fprintln(os.Stderr, "  TErrorCode addItem(TKey key, TKContactItem item)")
  fmt.Fprintln(os.Stderr, "  TErrorCode editItem(TKey key, TKContactItem item)")
  fmt.Fprintln(os.Stderr, "  TErrorCode deleteItem(TKey key, string pubKeyItem)")
  fmt.Fprintln(os.Stderr, "  TDataResult synContact(TKey key,  listPubKeyItemExist)")
  fmt.Fprintln(os.Stderr, "  TDataResult getLastConversation(TKey key, i32 numLast)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := ContactStore.NewTContactStoreServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "getData":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetData requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := ContactStore.TKey(argvalue0)
    fmt.Print(client.GetData(context.Background(), value0))
    fmt.Print("\n")
    break
  case "putData":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "PutData requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := ContactStore.TKey(argvalue0)
    arg23 := flag.Arg(2)
    mbTrans24 := thrift.NewTMemoryBufferLen(len(arg23))
    defer mbTrans24.Close()
    _, err25 := mbTrans24.WriteString(arg23)
    if err25 != nil {
      Usage()
      return
    }
    factory26 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt27 := factory26.GetProtocol(mbTrans24)
    argvalue1 := ContactStore.NewTKContact()
    err28 := argvalue1.Read(jsProt27)
    if err28 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.PutData(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "addItem":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "AddItem requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := ContactStore.TKey(argvalue0)
    arg30 := flag.Arg(2)
    mbTrans31 := thrift.NewTMemoryBufferLen(len(arg30))
    defer mbTrans31.Close()
    _, err32 := mbTrans31.WriteString(arg30)
    if err32 != nil {
      Usage()
      return
    }
    factory33 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt34 := factory33.GetProtocol(mbTrans31)
    argvalue1 := ContactStore.NewTKContactItem()
    err35 := argvalue1.Read(jsProt34)
    if err35 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.AddItem(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "editItem":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "EditItem requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := ContactStore.TKey(argvalue0)
    arg37 := flag.Arg(2)
    mbTrans38 := thrift.NewTMemoryBufferLen(len(arg37))
    defer mbTrans38.Close()
    _, err39 := mbTrans38.WriteString(arg37)
    if err39 != nil {
      Usage()
      return
    }
    factory40 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt41 := factory40.GetProtocol(mbTrans38)
    argvalue1 := ContactStore.NewTKContactItem()
    err42 := argvalue1.Read(jsProt41)
    if err42 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.EditItem(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "deleteItem":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "DeleteItem requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := ContactStore.TKey(argvalue0)
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.DeleteItem(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "synContact":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SynContact requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := ContactStore.TKey(argvalue0)
    arg46 := flag.Arg(2)
    mbTrans47 := thrift.NewTMemoryBufferLen(len(arg46))
    defer mbTrans47.Close()
    _, err48 := mbTrans47.WriteString(arg46)
    if err48 != nil { 
      Usage()
      return
    }
    factory49 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt50 := factory49.GetProtocol(mbTrans47)
    containerStruct1 := ContactStore.NewTContactStoreServiceSynContactArgs()
    err51 := containerStruct1.ReadField2(jsProt50)
    if err51 != nil {
      Usage()
      return
    }
    argvalue1 := containerStruct1.ListPubKeyItemExist
    value1 := argvalue1
    fmt.Print(client.SynContact(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "getLastConversation":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "GetLastConversation requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := ContactStore.TKey(argvalue0)
    tmp1, err53 := (strconv.Atoi(flag.Arg(2)))
    if err53 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.GetLastConversation(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
