swagger: "2.0"
info:
  title: Public Key-value store for trustkeys.network
  description: An awesome key-value store for mobile application that verify ECDSA
    digital signature with secp256k1
  version: 1.0.0
  termsOfService: https://kvpublic.trustkeys.network/swagger/
  contact:
    email: thanhnt@123xe.vn
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /tkcontact/AddNewContact/:
    post:
      tags:
      - tkcontact
      description: Add new contact to database
      operationId: TKContactController.Add New Contact
      parameters:
      - in: query
        name: pubKey
        description: Public key of a user
        required: true
        type: string
      - in: query
        name: sig
        description: Sign message
        required: true
        type: string
      - in: query
        name: mess
        description: message to sign
        required: true
        type: string
      responses:
        "200":
          description: '{string} string'
        "403":
          description: Error
  /tkcontact/EditContactItem/:
    post:
      tags:
      - tkcontact
      description: Edit person to Contact by pubKey
      operationId: TKContactController.Edit item contact
      parameters:
      - in: query
        name: pubKey
        description: "true"
        type: string
      - in: query
        name: sig
        description: "true"
        type: string
      - in: body
        name: body
        description: "true"
        schema:
          $ref: '#/definitions/models.TKContactItem'
      responses:
        "200":
          description: '{string} string'
        "403":
          description: :pubKey not found
  /tkcontact/GetContact/:
    get:
      tags:
      - tkcontact
      description: find object by objectid
      operationId: TKContactController.Get all contact
      parameters:
      - in: query
        name: pubKey
        description: Public key of a user
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TKContact'
        "403":
          description: :pubKey not found
  /tkcontact/PutContactItem/:
    post:
      tags:
      - tkcontact
      description: Add contact item to Contact by pubKey
      operationId: TKContactController.Add Contact Item
      parameters:
      - in: query
        name: pubKey
        description: Public key of a user
        required: true
        type: string
      - in: query
        name: sig
        description: Sign message
        required: true
        type: string
      - in: body
        name: body
        description: "true"
        schema:
          $ref: '#/definitions/models.TKContactItem'
      responses:
        "200":
          description: '{string} string'
        "403":
          description: Error
  /tkcontact/RemoveContactItem/:
    post:
      tags:
      - tkcontact
      description: Remove item in Contact by pubKey
      operationId: TKContactController.Remove item in contact
      parameters:
      - in: query
        name: pubKey
        description: "true"
        type: string
      - in: query
        name: sig
        description: "true"
        type: string
      - in: query
        name: pubKeyItem
        description: "true"
        type: string
      responses:
        "200":
          description: '{string} string'
        "403":
          description: Error
  /tkcontact/SynContact/:
    post:
      tags:
      - tkcontact
      description: Synchronization contact by pubKey
      operationId: TKContactController.Syn contact
      parameters:
      - in: query
        name: pubKey
        description: "true"
        type: string
      - in: query
        name: sig
        description: "true"
        type: string
      - in: body
        name: body
        description: "true"
        schema:
          $ref: '#/definitions/models.TKListPubKey'
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/models.TKContactItem'
        "403":
          description: Not found
definitions:
  models.TKContact:
    title: TKContact
    type: object
    properties:
      listFriends:
        type: array
        items:
          $ref: '#/definitions/models.TKContactItem'
      pubKey:
        type: string
  models.TKContactItem:
    title: TKContactItem
    type: object
    properties:
      birthDay:
        type: string
      coverPicture:
        type: string
      displayName:
        type: string
      emails:
        type: array
        items:
          type: string
      gender:
        type: integer
        format: int32
      phoneNumbers:
        type: array
        items:
          type: string
      profilePicture:
        type: string
      pubKeyHex:
        type: string
      timeAdd:
        type: string
  models.TKListPubKey:
    title: TKListPubKey
    type: object
    properties:
      listPubKey:
        type: array
        items:
          type: string
